---
# tasks file for httpd
- name: Install apache httpd
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: files/index.html  # Corrected the src path
    dest: /var/www/html/index.html  # Added index.html to the destination
    owner: root
    group: root
    mode: '0644'

